Redux Book Store: Feature/milestone 05
RailonA/Redux-BookStore pull request #5
Opened 2021-08-23 20:32 UTC by RailonA

Project-specific:

1- Review the design file from above and identify all the elements
2- Implement the styling of the different components based on the design. Remember that each element needs to look exactly the same as in the design.

2021-08-23 21:25 UTC, e71az requested changes
# Status:  Changes Required ♻️
_Check the comments under the review_
<hr>

Hello @RailonA, I am Elias, your reviewer for this PR

Well done so far with your project!

Your clone looks exactly like the given design, great job with that!!!

I will mention to you a small summary of things that need to be changed in order to keep moving:

- [ ] In the stylesheets of the app, make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
  - no repeating of the same rule

Please correct those issues and send another review request, good luck, and well done so far! 

Code review by Elias Castañeda

_(Feel free to leave any questions or comments in the PR thread if something is not 100% clear)_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-23 21:25 UTC, e71az commented on src/styles/book.css
> +  font-family: RobotoSlab, sans-serif;
- [ ] In this and your other style sheets you have CSS code repetition that could easily be solved with CSS variables, please do so. I will point out some of them, but please take a careful look at all of your CSS and look for these mistakes.

2021-08-23 21:25 UTC, e71az commented on src/styles/book.css
> +  line-height: normal;
- [ ] Code repetition, you could create 1 CSS class that has these 3 variables that don't change and use it where you need it in the HTML components.

2021-08-23 21:25 UTC, e71az commented on src/styles/book.css
> +  color: #4386bf;
- [ ] This color gets repeated a lot, please create a variable for it.

2021-08-24 14:37 UTC, rindrajosia requested changes
Hi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] I got errors related to proptype when I open your APP on my local machine. It will be nice if you fix it.
![1](https://user-images.githubusercontent.com/58552748/130635588-845deb5f-b34d-4738-9e1a-1632396f58c3.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/app.css
> +  display: flex;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/app.css
> +  display: flex;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/book.css
> +  font-family: RobotoSlab, sans-serif;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/book.css
> +  font-family: RobotoSlab, sans-serif;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/book.css
> +  display: flex;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/book.css
> +  display: flex;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/book.css
> +  font-family: RobotoSlab, sans-serif;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/book.css
> +  font-family: RobotoSlab, sans-serif;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/bookList.css
> +  align-items: center;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 14:37 UTC, rindrajosia commented on src/styles/bookList.css
> +  align-items: center;
- [ ] [REQUIRED] Please make sure that the same rule is not repeated

2021-08-24 16:25 UTC, bellom commented on src/styles/app.css
> +  display: flex;
Your CSS appears to be WET-(Write Every Time), Microverse encourage DRY-(Don't Repeat Yourself) code.

Let's improve our styling by using [Combine Elements](https://speckyboy.com/good-bad-css-practices)

Example:

You have `display: flex` written more than twice, which is simply a repetition of rules;

You could have it this way;
```
.react-logo, .flex-row {
    display: flex
}
```
**Kindly combine all repeated rules in this file.**

OR

 Create a rule.
```
.someCommonStyle {
  display: flex
}
```
Then we apply this style to all the elements with this rule. Doing this will make our code cleaner and easier to maintain

2021-08-24 16:26 UTC, bellom commented on src/styles/book.css
> +  font-family: RobotoSlab, sans-serif;
**Kindly combine all repeated rules in this file.**

2021-08-24 16:29 UTC, bellom commented on src/styles/bookList.css
> +  align-items: center;
@RailonA 

**Kindly combine all repeated rules in this file.**

2021-08-24 16:30 UTC, bellom requested changes
## Hi @RailonA   :clap: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments above and below**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

2021-08-24 16:31 UTC, bellom requested changes

2021-08-24 16:31 UTC, bellom commented on src/styles/app.css
> +  display: flex;
@RailonA I'm afraid we need to attend to the repetition of CSS rules mentioned by the previous CR 👆 above.

In another word;

Your CSS appears to be WET-(Write Every Time), Microverse encourage DRY-(Don't Repeat Yourself) code.

Let's improve our styling by using [Combine Elements](https://speckyboy.com/good-bad-css-practices)

Example:

You have `display: flex` written more than twice, which is simply a repetition of rules;

You could have it this way;
```
.react-logo, .flex-row {
    display: flex
}
```
**Kindly combine all repeated rules in this file.**

OR

 Create a rule.
```
.someCommonStyle {
  display: flex
}
```
Then we apply this style to all the elements with this rule. Doing this will make our code cleaner and easier to maintain

2021-08-24 17:07 UTC, addod19 commented on src/styles/book.css
> +  display: flex;
- [ ] It would be better if we address the comments outlined by the previous code reviewer. We still have repeating rules

2021-08-24 17:13 UTC, addod19 requested changes
### Hi @RailonA, 

Great work on making the changes requested by a previous reviewer 👏 The App.css file is now DRY, however, other CSS files need a little bit of work :muscle: 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

**NB**: There is no commit after the comment from the previous code reviewer. The comment must be addressed

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

__Happy coding__ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-08-24 22:21 UTC, taiwo2 approved these changes
#STATUS: Approved 🎉 
@RailonA congratulations for try hard to implement the suggested changes from the previous Code Reviewers, it's time to merge.

2021-08-24 22:22 UTC, merged